import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { api, ApiContext, ApiError, AuditEvent, CanonicalAccount, Engagement, ReportLine, TrialBalanceLine } from "./api";

type View = "data" | "mapping" | "accounts" | "history";
type CsvRow = { accountCode: string; accountName: string; debit: string; credit: string };
const gbp = new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" });
const fullDate = new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" });
const dateTime = new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
const amount = (line: TrialBalanceLine) => Number(line.debit || 0) - Number(line.credit || 0);
const money = (value: number) => value < 0 ? `(${gbp.format(Math.abs(value))})` : gbp.format(value);
const title = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/(^|\s)\S/g, letter => letter.toUpperCase());

function parseCsv(text: string): CsvRow[] {
  const data: string[][] = []; let row: string[] = [], field = "", quoted = false;
  for (let i = 0; i < text.length; i++) { const char = text[i];
    if (char === '"' && quoted && text[i + 1] === '"') { field += '"'; i++; }
    else if (char === '"') quoted = !quoted;
    else if (char === "," && !quoted) { row.push(field.trim()); field = ""; }
    else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[i + 1] === "\n") i++; row.push(field.trim()); if (row.some(Boolean)) data.push(row); row = []; field = ""; }
    else field += char;
  }
  row.push(field.trim()); if (row.some(Boolean)) data.push(row); if (data.length < 2) return [];
  const headers = data[0].map(v => v.toLowerCase().replace(/[^a-z]/g, ""));
  const find = (...names: string[]) => headers.findIndex(v => names.includes(v));
  const indexes = [find("accountcode", "code", "nominalcode"), find("accountname", "name", "description", "nominalname"), find("debit", "debits"), find("credit", "credits")];
  if (indexes.some(i => i < 0)) return [];
  return data.slice(1).map(v => ({ accountCode: v[indexes[0]] || "", accountName: v[indexes[1]] || "", debit: v[indexes[2]] || "", credit: v[indexes[3]] || "" }));
}

function Empty({ heading, body, children }: React.PropsWithChildren<{ heading: string; body: string }>) { return <div className="empty"><span>＋</span><h3>{heading}</h3><p>{body}</p>{children}</div>; }
function Skeleton() { return <div className="skeleton" aria-label="Loading">{Array.from({ length: 7 }, (_, i) => <i key={i} />)}</div>; }

export function App() {
  const [context, setContext] = useState<ApiContext>(() => ({ tenantId: localStorage.getItem("accounts.tenantId") || import.meta.env.VITE_TENANT_ID || "", actorId: localStorage.getItem("accounts.actorId") || import.meta.env.VITE_ACTOR_ID || "" }));
  const [draftContext, setDraftContext] = useState(context);
  const [engagements, setEngagements] = useState<Engagement[]>([]); const [selectedId, setSelectedId] = useState("");
  const [lines, setLines] = useState<TrialBalanceLine[]>([]); const [events, setEvents] = useState<AuditEvent[]>([]); const [report, setReport] = useState<ReportLine[]>([]); const [view, setView] = useState<View>("data");
  const [canonicalAccounts, setCanonicalAccounts] = useState<CanonicalAccount[]>([]); const [taxonomyError, setTaxonomyError] = useState("");
  const [loading, setLoading] = useState(false); const [detailLoading, setDetailLoading] = useState(false); const [error, setError] = useState(""); const [detailError, setDetailError] = useState(""); const [reportError, setReportError] = useState(""); const [historyError, setHistoryError] = useState("");
  const [notice, setNotice] = useState<{ good: boolean; text: string } | null>(null); const [importFile, setImportFile] = useState<File | null>(null); const [csvRows, setCsvRows] = useState<CsvRow[]>([]); const [importError, setImportError] = useState(""); const [importing, setImporting] = useState(false); const [saving, setSaving] = useState("");
  const fileRef = useRef<HTMLInputElement>(null); const modalRef = useRef<HTMLElement>(null); const returnFocusRef = useRef<HTMLElement | null>(null); const configured = Boolean(context.tenantId && context.actorId); const engagement = engagements.find(item => item.id === selectedId);
  const loadEngagements = useCallback(async () => { if (!configured) return; setLoading(true); setError(""); setTaxonomyError(""); api.canonicalAccounts(context).then(data => setCanonicalAccounts(data.items)).catch(e => { setCanonicalAccounts([]); setTaxonomyError(e instanceof Error ? e.message : "Could not load canonical accounts."); }); try { const data = await api.engagements(context); setEngagements(data.items); setSelectedId(current => data.items.some(item => item.id === current) ? current : data.items[0]?.id || ""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load engagements."); } finally { setLoading(false); } }, [configured, context]);
  const loadDetail = useCallback(async () => { if (!selectedId) { setLines([]); setEvents([]); setReport([]); setReportError(""); setHistoryError(""); return; } setDetailLoading(true); setDetailError(""); setReportError(""); setHistoryError(""); const [tb, history, reportData] = await Promise.allSettled([api.trialBalance(context, selectedId), api.history(context, selectedId), api.report(context, selectedId)]); if (tb.status === "fulfilled") setLines(tb.value.items); else { setLines([]); setDetailError(tb.reason?.message || "Could not load the trial balance."); } if (history.status === "fulfilled") setEvents(history.value.items); else { setEvents([]); setHistoryError(history.reason?.message || "Could not load engagement history."); } if (reportData.status === "fulfilled") setReport(reportData.value.lines); else { setReport([]); if (!(reportData.reason instanceof ApiError && reportData.reason.status === 404)) setReportError(reportData.reason?.message || "Could not load the draft accounts."); } setDetailLoading(false); }, [context, selectedId]);
  useEffect(() => { loadEngagements(); }, [loadEngagements]); useEffect(() => { loadDetail(); }, [loadDetail]);
  useEffect(() => {
    if (!importFile) return;
    modalRef.current?.focus();
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && !importing) { event.preventDefault(); closeImport(); return; }
      if (event.key !== "Tab" || !modalRef.current) return;
      const controls = [...modalRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')];
      if (!controls.length) return;
      const first = controls[0], last = controls[controls.length - 1];
      if (event.shiftKey && (document.activeElement === first || document.activeElement === modalRef.current)) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [importFile, importing]);

  const mapped = lines.filter(line => line.canonical_code).length, unmapped = lines.length - mapped, debit = lines.reduce((n, line) => n + Number(line.debit || 0), 0), credit = lines.reduce((n, line) => n + Number(line.credit || 0), 0);
  const options = useMemo(() => canonicalAccounts.map(account => [account.id, `${account.canonical_code} · ${account.name}`]), [canonicalAccounts]);

  function saveContext(e: React.FormEvent) { e.preventDefault(); const next = { tenantId: draftContext.tenantId.trim(), actorId: draftContext.actorId.trim() }; localStorage.setItem("accounts.tenantId", next.tenantId); localStorage.setItem("accounts.actorId", next.actorId); setContext(next); }
  function openImport() { returnFocusRef.current = document.activeElement as HTMLElement | null; fileRef.current?.click(); }
  function closeImport() { setImportFile(null); setCsvRows([]); setImportError(""); requestAnimationFrame(() => returnFocusRef.current?.focus()); }
  async function chooseFile(file?: File) { setImportFile(file || null); setCsvRows([]); setImportError(""); if (!file) return; if (!file.name.toLowerCase().endsWith(".csv")) { setImportError("Choose a CSV file."); return; } if (file.size > 10485760) { setImportError("The file must be smaller than 10 MB."); return; } const rows = parseCsv(await file.text()); if (!rows.length) setImportError("Expected account code, account name, debit and credit columns."); else setCsvRows(rows); }
  async function commitImport() { if (!importFile) return; setImporting(true); setImportError(""); try { await api.importTrialBalance(context, selectedId, importFile); setNotice({ good: true, text: `${importFile.name} was imported.` }); closeImport(); await loadDetail(); } catch (e) { setImportError(e instanceof ApiError && e.status === 404 ? "Import is ready, but the API import route has not been deployed yet." : e instanceof Error ? e.message : "Import failed."); } finally { setImporting(false); } }
  async function saveMapping(line: TrialBalanceLine, canonicalAccountId: string) { if (!canonicalAccountId) return; setSaving(line.account_code); setNotice(null); try { await api.updateMapping(context, selectedId, line.source_account_id, canonicalAccountId); setNotice({ good: true, text: `${line.account_code} · ${line.account_name} was mapped.` }); await loadDetail(); } catch (e) { setNotice({ good: false, text: e instanceof Error ? e.message : "Mapping failed." }); } finally { setSaving(""); } }

  const views: { id: View; label: string; count?: number }[] = [{ id: "data", label: "Source data" }, { id: "mapping", label: "Mapping", count: unmapped || undefined }, { id: "accounts", label: "Draft accounts" }, { id: "history", label: "History", count: events.length || undefined }];
  return <div className="app-shell"><header className="topbar"><a className="brand" href="/"><span>LD</span><b>Ledgerly</b></a><div className="top-actions"><i className={error ? "down" : ""} aria-hidden="true" /><span>{error ? "Service issue" : "Workspace connected"}</span><button className="avatar" type="button" aria-label="Open account menu">{(context.actorId || "AC").slice(0, 2).toUpperCase()}</button></div></header><div className="workspace">
    <aside className="sidebar"><p className="eyebrow">Accounts workspace</p><label htmlFor="engagement">Engagement</label><select id="engagement" value={selectedId} onChange={e => setSelectedId(e.target.value)} disabled={loading || !engagements.length}><option value="">{loading ? "Loading…" : "Select engagement"}</option>{engagements.map(item => <option key={item.id} value={item.id}>{item.legal_name} · {new Date(item.period_end).getFullYear()}</option>)}</select><nav>{views.map(item => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => setView(item.id)}><span>{item.id === "data" ? "↓" : item.id === "mapping" ? "↗" : item.id === "accounts" ? "≡" : "◷"}</span>{item.label}{item.count ? <em>{item.count}</em> : null}</button>)}</nav><div className="progress"><span>Period progress</span><b>{lines.length ? Math.round(mapped / lines.length * 100) : 0}%</b><div><i style={{ width: `${lines.length ? mapped / lines.length * 100 : 0}%` }} /></div><small>{unmapped ? `${unmapped} mapping decisions remaining` : lines.length ? "Ready for review" : "Waiting for source data"}</small></div></aside>
    <main className="content">{!configured ? <section className="setup"><p className="eyebrow">Connect your workspace</p><h1>Enter your access context</h1><p>The API uses these identifiers to keep client workspaces isolated.</p><form onSubmit={saveContext}><label>Tenant ID<input value={draftContext.tenantId} onChange={e => setDraftContext({ ...draftContext, tenantId: e.target.value })} required /></label><label>Actor ID<input value={draftContext.actorId} onChange={e => setDraftContext({ ...draftContext, actorId: e.target.value })} required /></label><button className="primary">Connect workspace</button></form></section> : loading ? <Skeleton /> : error ? <section className="error-state"><span>!</span><h1>We couldn’t open this workspace</h1><p>{error}</p><button className="primary" onClick={loadEngagements}>Try again</button></section> : !engagements.length ? <Empty heading="No engagements yet" body="Create an engagement through the accounts service to begin preparing a period." /> : <>
      <section className="page-head"><div><p>Engagements <b>/</b> {engagement?.legal_name}</p><div><h1>{engagement?.legal_name}</h1><span>{title(engagement?.status || "preparation")}</span></div><small>Year ended {engagement && fullDate.format(new Date(engagement.period_end))} · {engagement?.framework} · Version {engagement?.version}</small></div><button className="secondary" onClick={() => setContext({ tenantId: "", actorId: "" })}>Workspace settings</button></section>
      {notice && <div className={`notice ${notice.good ? "good" : "bad"}`} role="status"><b>{notice.good ? "Saved" : "Action needed"}</b>{notice.text}<button type="button" onClick={() => setNotice(null)} aria-label="Dismiss notification">×</button></div>}
      {detailLoading ? <Skeleton /> : detailError ? <div className="inline-error"><div><b>Couldn’t load engagement data</b><p>{detailError}</p></div><button className="secondary" onClick={loadDetail}>Retry</button></div> : view === "data" ? <DataView lines={lines} debit={debit} credit={credit} fileRef={fileRef} chooseFile={chooseFile} openImport={openImport} /> : view === "mapping" ? <MappingView lines={lines} options={options} mapped={mapped} unmapped={unmapped} saving={saving} onSave={saveMapping} taxonomyError={taxonomyError} onRetryTaxonomy={loadEngagements} /> : view === "accounts" ? <AccountsView engagement={engagement} lines={lines} report={report} error={reportError} onRetry={loadDetail} /> : <HistoryView events={events} error={historyError} onRefresh={loadDetail} />}
    </>}</main></div>
    {importFile && <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget && !importing) closeImport(); }}><section ref={modalRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="import-title" aria-describedby="import-summary" tabIndex={-1}><div className="modal-head"><div><p className="eyebrow">Import source data</p><h2 id="import-title">Review trial balance</h2></div><button type="button" onClick={closeImport} aria-label="Close import dialog" disabled={importing}>×</button></div><div className="file-card" id="import-summary"><span>CSV</span><div><b>{importFile.name}</b><small>{(importFile.size / 1024).toFixed(1)} KB · {csvRows.length} rows detected</small></div><button type="button" onClick={() => fileRef.current?.click()} disabled={importing}>Replace file</button></div>{importError && <p className="form-error" role="alert">{importError}</p>}{csvRows.length > 0 && <div className="preview"><table><thead><tr><th>Code</th><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{csvRows.slice(0, 5).map((row, i) => <tr key={i}><td>{row.accountCode}</td><td>{row.accountName}</td><td>{row.debit || "—"}</td><td>{row.credit || "—"}</td></tr>)}</tbody></table>{csvRows.length > 5 && <small>Plus {csvRows.length - 5} more rows</small>}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={closeImport} disabled={importing}>Cancel</button><button type="button" className="primary" onClick={commitImport} disabled={!csvRows.length || importing}>{importing ? "Importing…" : `Import ${csvRows.length || ""} rows`}</button></div></section></div>}
  </div>;
}

function DataView({ lines, debit, credit, fileRef, chooseFile, openImport }: { lines: TrialBalanceLine[]; debit: number; credit: number; fileRef: React.RefObject<HTMLInputElement | null>; chooseFile: (file?: File) => void; openImport: () => void }) { return <><div className="metrics"><div><span>Total debits</span><b>{money(debit)}</b></div><div><span>Total credits</span><b>{money(credit)}</b></div><div><span>Difference</span><b className={Math.abs(debit-credit) > .005 ? "danger" : "success"}>{money(debit-credit)}</b></div><div><span>Source accounts</span><b>{lines.length}</b></div></div><section className="panel"><PanelHead eyebrow="Data" heading="Trial balance" body="The latest committed source balances for this period."><button type="button" className="primary" onClick={openImport}>Import trial balance</button><input hidden ref={fileRef} type="file" accept=".csv,text/csv" aria-label="Choose trial balance CSV" onChange={e => { chooseFile(e.target.files?.[0]); e.target.value = ""; }} /></PanelHead>{!lines.length ? <Empty heading="No trial balance imported" body="Import a CSV with account code, account name, debit and credit columns."><button type="button" className="primary" onClick={openImport}>Choose CSV file</button></Empty> : <div className="table-wrap"><table><thead><tr><th>Account</th><th>Account name</th><th className="number">Debit</th><th className="number">Credit</th><th>Status</th></tr></thead><tbody>{lines.map(line => <tr key={line.account_code}><td className="mono">{line.account_code}</td><td><b>{line.account_name}</b></td><td className="number">{Number(line.debit) ? money(Number(line.debit)) : "—"}</td><td className="number">{Number(line.credit) ? money(Number(line.credit)) : "—"}</td><td><span className={`tag ${line.canonical_code ? "ok" : "warning"}`}>{line.canonical_code ? "Mapped" : "Needs mapping"}</span></td></tr>)}</tbody><tfoot><tr><td colSpan={2}>Control total</td><td className="number">{money(debit)}</td><td className="number">{money(credit)}</td><td /></tr></tfoot></table></div>}</section></>; }
function PanelHead({ eyebrow, heading, body, children }: React.PropsWithChildren<{ eyebrow: string; heading: string; body: string }>) { return <div className="panel-head"><div><p className="eyebrow">{eyebrow}</p><h2>{heading}</h2><small>{body}</small></div>{children}</div>; }
function MappingView({ lines, options, mapped, unmapped, saving, onSave, taxonomyError, onRetryTaxonomy }: { lines: TrialBalanceLine[]; options: string[][]; mapped: number; unmapped: number; saving: string; onSave: (line: TrialBalanceLine, code: string) => void; taxonomyError: string; onRetryTaxonomy: () => void }) { return <div className="mapping-layout"><section className="panel"><PanelHead eyebrow="Classification" heading="Account mapping" body="Connect each source account to the reporting taxonomy."><span className={`summary ${unmapped ? "pending" : "complete"}`}>{unmapped ? `${unmapped} to review` : "All mapped"}</span></PanelHead>{taxonomyError && <PanelError heading="Canonical accounts unavailable" message={taxonomyError} onRetry={onRetryTaxonomy} />}{!lines.length ? <Empty heading="Nothing to map" body="Import a trial balance before mapping source accounts." /> : <div className="table-wrap"><table><thead><tr><th>Source account</th><th className="number">Balance</th><th>Canonical account</th></tr></thead><tbody>{lines.map(line => <tr key={line.account_code}><td><small className="mono">{line.account_code}</small><b className="block">{line.account_name}</b></td><td className="number">{money(amount(line))}</td><td><select aria-label={`Canonical account for ${line.account_code} ${line.account_name}`} className={!line.canonical_account_id ? "select-warning" : ""} value={line.canonical_account_id || ""} disabled={Boolean(taxonomyError) || saving === line.account_code} onChange={e => onSave(line, e.target.value)}><option value="">Select canonical account…</option>{line.canonical_account_id && !options.some(([id]) => id === line.canonical_account_id) && <option value={line.canonical_account_id}>{line.canonical_code} · {line.canonical_name}</option>}{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></td></tr>)}</tbody></table></div>}</section><aside className="guidance"><i aria-hidden="true">i</i><h3>Mapping control</h3><p>Every source account must be mapped before this period can move to review.</p><dl><div><dt>Mapped</dt><dd>{mapped}</dd></div><div><dt>Unmapped</dt><dd>{unmapped}</dd></div></dl><small>Changes are recorded in the immutable engagement history.</small></aside></div>; }

const statementLabels: Record<string, string> = { SOFA: "Statement of financial activities", IS: "Income statement", PNL: "Profit and loss account", BS: "Balance sheet", SFP: "Statement of financial position", CASH_FLOW: "Cash flow statement", CF: "Cash flow statement" };
function AccountsView({ engagement, lines, report, error, onRetry }: { engagement?: Engagement; lines: TrialBalanceLine[]; report: ReportLine[]; error: string; onRetry: () => void }) { const statements = [...new Map(report.map(row => [row.statement_code, report.filter(item => item.statement_code === row.statement_code)])).entries()]; return <section className="panel report"><PanelHead eyebrow="Draft accounts" heading="Draft financial statements" body="Draft figures grouped by the reporting service statement codes."><span className="summary pending">Unaudited draft</span></PanelHead>{error ? <PanelError heading="Draft accounts unavailable" message={error} onRetry={onRetry} /> : !report.length ? <Empty heading="No reportable balances" body={lines.length ? "Map source accounts to populate the draft accounts." : "Import and map a trial balance to populate the draft accounts."} /> : <div className="report-sheet"><div className="report-title"><b>{engagement?.legal_name}</b><small>Year ended {engagement && fullDate.format(new Date(engagement.period_end))}</small></div>{statements.map(([statementCode, rows]) => <section className="statement" key={statementCode}><h3>{statementLabels[statementCode] || title(statementCode)}</h3><table><thead><tr><th>Reporting line</th><th>Provenance</th><th className="number">Current period</th></tr></thead><tbody>{rows.map(row => <tr key={row.code}><td><small className="mono">{row.code}</small><b className="block">{row.caption}</b></td><td className="muted">{row.source_account_ids.length} source {row.source_account_ids.length === 1 ? "account" : "accounts"}</td><td className="number"><b>{money(Number(row.balance))}</b></td></tr>)}</tbody></table></section>)}<p>Draft generated from version {engagement?.version}. Figures retain source-account provenance.</p></div>}</section>; }
function PanelError({ heading, message, onRetry }: { heading: string; message: string; onRetry: () => void }) { return <div className="panel-error" role="alert"><div><b>{heading}</b><p>{message}</p></div><button type="button" className="secondary" onClick={onRetry}>Retry</button></div>; }
function HistoryView({ events, error, onRefresh }: { events: AuditEvent[]; error: string; onRefresh: () => void }) { return <section className="panel"><PanelHead eyebrow="Audit trail" heading="Engagement history" body="An immutable record of material activity."><button type="button" className="secondary" onClick={onRefresh}>Refresh</button></PanelHead>{error ? <PanelError heading="History unavailable" message={error} onRetry={onRefresh} /> : !events.length ? <Empty heading="No history recorded" body="Import and mapping activity will appear here when it is committed." /> : <ol className="timeline">{events.map(event => <li key={event.event_id}><i aria-hidden="true" /><div><header><b>{title(event.event_type)}</b><time dateTime={event.occurred_at_utc}>{dateTime.format(new Date(event.occurred_at_utc))}</time></header><p>{event.reason || `${title(event.object_type)} ${event.object_id}`}</p><small>Actor {event.actor_id} · Ref {event.correlation_id.slice(0,8)}</small></div></li>)}</ol>}</section>; }
