import { useCallback, useEffect, useState } from "react";
import {
  Badge, Button, Field, Input, Select, Skeleton, SkeletonItem, Table, TableBody,
  TableCell, TableHeader, TableHeaderCell, TableRow, MessageBar, MessageBarBody,
} from "@fluentui/react-components";
import { api, type ApiContext, type CrmOpportunity, type CrmProspect, type OnboardingCase, type PlatformTeam, type PracticeService, type ResourceProfile } from "./api";
import { formatDate } from "./displayFormat";
import { statutoryLabel } from "./format";
import { statusBadgeProps } from "./statusBadge";
import "./practice-management.css";

export type CrmOnboardingView = "prospects" | "opportunities" | "onboarding";
type Props = { view: CrmOnboardingView; context: ApiContext; onOpenQuoteBench?: (opportunityId: string) => void };

const label = statutoryLabel;
const date = (value?: string | null) => formatDate(value, "Not set");
const errorText = (value: unknown) => value instanceof Error ? value.message : "The request could not be completed.";
function Status({ value }: { value: string }) { return <Badge {...statusBadgeProps(value)}>{label(value)}</Badge>; }
function Head({ title, body }: { title: string; body: string }) { return <header className="pm-head"><div><h1>{title}</h1><p>{body}</p></div></header>; }
function Loading({ text }: { text: string }) { return <Skeleton className="pm-loading" aria-label={text} role="status"><SkeletonItem size={24} /><SkeletonItem /><SkeletonItem /></Skeleton>; }
function Failure({ message, retry }: { message: string; retry: () => void }) { return <MessageBar intent="error"><MessageBarBody>{message}</MessageBarBody><Button appearance="transparent" onClick={retry}>Retry</Button></MessageBar>; }

export default function CrmOnboarding({ view, context, onOpenQuoteBench }: Props) {
  if (view === "prospects") return <Prospects context={context} />;
  if (view === "opportunities") return <Opportunities context={context} onOpenQuoteBench={onOpenQuoteBench} />;
  return <Onboarding context={context} />;
}

function Prospects({ context }: { context: ApiContext }) {
  const [items, setItems] = useState<CrmProspect[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [selected, setSelected] = useState<CrmProspect | null>(null), [resources, setResources] = useState<ResourceProfile[]>([]), [teams, setTeams] = useState<PlatformTeam[]>([]), [saving, setSaving] = useState(false);
  const [name, setName] = useState(""), [entityType, setEntityType] = useState("COMPANY"), [source, setSource] = useState("");
  const [editName, setEditName] = useState(""), [editLegalName, setEditLegalName] = useState(""), [editSource, setEditSource] = useState(""), [editStatus, setEditStatus] = useState<CrmProspect["status"]>("prospect"), [editOwner, setEditOwner] = useState(""), [editTeam, setEditTeam] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await api.crmProspects(context)).items); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [context]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: React.FormEvent) { event.preventDefault(); try { await api.createCrmProspect(context, { displayName: name, entityType, source: source || undefined, contactIds: [] }); setName(""); setSource(""); await load(); } catch (e) { setError(errorText(e)); } }
  function setEditFields(item: CrmProspect) { setEditName(item.display_name); setEditLegalName(item.legal_name || ""); setEditSource(item.source || ""); setEditStatus(item.status); setEditOwner(item.responsible_member_id || ""); setEditTeam(item.responsible_team_id || ""); }
  async function open(item: CrmProspect) { setError(""); try { const detail = await api.crmProspect(context, item.id); setSelected(detail.item); setEditFields(detail.item); const [resourceResult, teamResult] = await Promise.allSettled([api.resourceProfiles(context), api.platformTeams(context)]); setResources(resourceResult.status === "fulfilled" ? resourceResult.value.items.filter((resource) => resource.status === "active") : []); setTeams(teamResult.status === "fulfilled" ? teamResult.value.items.filter((team) => team.status === "ACTIVE") : []); } catch (e) { setError(errorText(e)); } }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(""); try { await api.updateCrmProspect(context, selected.id, { displayName: editName, legalName: editLegalName, source: editSource, status: editStatus, responsibleMemberId: editOwner, responsibleTeamId: editTeam }); const detail = await api.crmProspect(context, selected.id); setSelected(detail.item); setEditFields(detail.item); await load(); } catch (e) { setError(errorText(e)); } finally { setSaving(false); } }
  if (loading) return <Loading text="Loading prospects" />;
  if (selected) return <section className="pm-page"><Button appearance="subtle" onClick={() => setSelected(null)}>Back to prospects</Button><Head title={selected.display_name} body={`${label(selected.entity_type)} · ${label(selected.status)}`} />{error && <Failure message={error} retry={() => void open(selected)} />}
    <section className="pm-section"><header><div><h2>Prospect details</h2><p>Update the relationship record before it is converted to a client.</p></div><Status value={selected.status} /></header>
      {selected.status === "converted" ? <MessageBar><MessageBarBody>This prospect has been converted and is read-only. Open the client record to manage the ongoing relationship.</MessageBarBody></MessageBar> : <form className="pm-edit-grid" onSubmit={save}>
        <Field label="Prospect name" required><Input value={editName} maxLength={240} onChange={(_, data) => setEditName(data.value)} /></Field>
        <Field label="Legal name"><Input value={editLegalName} maxLength={240} onChange={(_, data) => setEditLegalName(data.value)} /></Field>
        <Field label="Source"><Input value={editSource} maxLength={120} onChange={(_, data) => setEditSource(data.value)} /></Field>
        <Field label="Status"><Select value={editStatus} onChange={(_, data) => setEditStatus(data.value as CrmProspect["status"])}>{["prospect","qualified","lost","archived"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></Field>
        <Field label="Owner"><Select value={editOwner} onChange={(_, data) => setEditOwner(data.value)}><option value="">Unassigned</option>{editOwner && !resources.some((resource) => resource.id === editOwner) && <option value={editOwner}>{selected.responsible_member_name || "Current owner"}</option>}{resources.map((resource) => <option key={resource.id} value={resource.id}>{resource.display_name}</option>)}</Select></Field>
        <Field label="Team"><Select value={editTeam} onChange={(_, data) => setEditTeam(data.value)}><option value="">Unassigned</option>{editTeam && !teams.some((team) => team.id === editTeam) && <option value={editTeam}>{selected.responsible_team_name || "Current team"}</option>}{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</Select></Field>
        <div className="pm-form-actions"><Button type="button" onClick={() => setEditFields(selected)}>Cancel changes</Button><Button appearance="primary" type="submit" disabled={!editName.trim() || saving}>{saving ? "Saving…" : "Save changes"}</Button></div>
      </form>}
    </section>
    <section className="pm-section"><header><h2>Contacts</h2></header>{selected.contacts?.length ? <Table aria-label="Prospect contacts"><TableHeader><TableRow><TableHeaderCell>Contact</TableHeaderCell><TableHeaderCell>Relationship</TableHeaderCell></TableRow></TableHeader><TableBody>{selected.contacts.map((contact, index) => <TableRow key={String(contact.id ?? index)}><TableCell>{String(contact.display_name ?? "Contact")}</TableCell><TableCell>{label(String(contact.relationship_type ?? "contact"))}</TableCell></TableRow>)}</TableBody></Table> : <p>No contacts are linked to this prospect.</p>}</section>
    <section className="pm-section"><header><h2>Activity</h2></header>{selected.activities?.length ? <Table aria-label="Prospect activity"><TableHeader><TableRow><TableHeaderCell>Activity</TableHeaderCell><TableHeaderCell>Date</TableHeaderCell></TableRow></TableHeader><TableBody>{selected.activities.map((activity, index) => <TableRow key={String(activity.id ?? index)}><TableCell>{String(activity.summary ?? label(String(activity.activity_type ?? "activity")))}</TableCell><TableCell>{date(String(activity.occurred_at ?? ""))}</TableCell></TableRow>)}</TableBody></Table> : <p>No activity has been recorded.</p>}</section>
  </section>;
  return <section className="pm-page"><Head title="Prospects" body="Pre-client relationships that convert into the canonical client master only after controlled acceptance." />{error && <Failure message={error} retry={load} />}
    <section className="pm-section"><header><div><h2>Add prospect</h2><p>Use the common contact record; a client is not created at this stage.</p></div></header><form className="pm-add-row" onSubmit={create}><Field label="Prospect name" required><Input value={name} maxLength={240} onChange={(_, data) => setName(data.value)} /></Field><Field label="Entity type"><Select value={entityType} onChange={(_, data) => setEntityType(data.value)}>{["COMPANY","PARTNERSHIP","SOLE_TRADER","INDIVIDUAL","CHARITY","TRUST","OTHER"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></Field><Field label="Source"><Input value={source} maxLength={120} onChange={(_, data) => setSource(data.value)} /></Field><Button appearance="primary" type="submit" disabled={!name.trim()}>Add prospect</Button></form></section>
    <div className="pm-grid-scroll"><Table aria-label="CRM prospects"><TableHeader><TableRow><TableHeaderCell>Prospect</TableHeaderCell><TableHeaderCell>Primary contact</TableHeaderCell><TableHeaderCell>Open opportunities</TableHeaderCell><TableHeaderCell>Owner / team</TableHeaderCell><TableHeaderCell>Source</TableHeaderCell><TableHeaderCell>Last activity</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell><Button appearance="transparent" onClick={() => void open(item)}>{item.display_name}</Button><small>{item.legal_name || label(item.entity_type)}</small></TableCell><TableCell>{item.primary_contact_name || "Not set"}{item.primary_contact_email && <small>{item.primary_contact_email}</small>}</TableCell><TableCell>{item.open_opportunities ?? 0}</TableCell><TableCell>{[item.responsible_member_name, item.responsible_team_name].filter(Boolean).join(" · ") || "Unassigned"}</TableCell><TableCell>{item.source || "Not recorded"}</TableCell><TableCell>{date(item.last_activity_at)}</TableCell><TableCell><Status value={item.status} /></TableCell></TableRow>)}</TableBody></Table></div>
  </section>;
}

function Opportunities({ context, onOpenQuoteBench }: { context: ApiContext; onOpenQuoteBench?: (opportunityId: string) => void }) {
  const [items, setItems] = useState<CrmOpportunity[]>([]), [prospects, setProspects] = useState<CrmProspect[]>([]), [services, setServices] = useState<PracticeService[]>([]);
  const [selected, setSelected] = useState<CrmOpportunity | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [name, setName] = useState(""), [prospectId, setProspectId] = useState(""), [serviceId, setServiceId] = useState(""), [expectedCloseDate, setExpectedCloseDate] = useState("");
  const [proposalId, setProposalId] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [opportunityData, prospectData, serviceData] = await Promise.all([api.crmOpportunities(context), api.crmProspects(context), api.practiceServices(context)]); setItems(opportunityData.items); setProspects(prospectData.items.filter((item) => !["converted","archived"].includes(item.status))); setServices(serviceData.items.filter((item) => item.status === "active")); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [context]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: React.FormEvent) { event.preventDefault(); try { await api.createCrmOpportunity(context, { name, prospectId, serviceIds: [serviceId], expectedCloseDate: expectedCloseDate || undefined, currency: "GBP" }); setName(""); setExpectedCloseDate(""); await load(); } catch (e) { setError(errorText(e)); } }
  async function open(item: CrmOpportunity) { try { setSelected((await api.crmOpportunity(context, item.id)).item); } catch (e) { setError(errorText(e)); } }
  async function stage(stageKey: string) { if (!selected) return; try { await api.updateOpportunityStage(context, selected.id, stageKey); const detail = (await api.crmOpportunity(context, selected.id)).item; setSelected(detail); await load(); } catch (e) { setError(errorText(e)); } }
  async function linkProposal() { if (!selected || !proposalId.trim()) return; try { await api.linkQuoteBenchProposal(context, selected.id, proposalId.trim()); setProposalId(""); setSelected((await api.crmOpportunity(context, selected.id)).item); await load(); } catch (e) { setError(errorText(e)); } }
  if (loading) return <Loading text="Loading opportunities" />;
  if (selected) return <section className="pm-page"><Button appearance="subtle" onClick={() => setSelected(null)}>Back to opportunities</Button><Head title={selected.name} body={`${selected.relationship_name || "Commercial relationship"} · ${label(selected.stage_key)}`} />{error && <Failure message={error} retry={() => void open(selected)} />}
    <section className="pm-section"><header><div><h2>Opportunity</h2><p>Commercial progress, proposed Practice services and QuoteBench reference.</p></div><Status value={selected.status} /></header><dl className="pm-facts"><div><dt>Relationship</dt><dd>{selected.relationship_name || "Not set"}</dd></div><div><dt>Expected close</dt><dd>{date(selected.expected_close_date)}</dd></div><div><dt>Value</dt><dd>{selected.estimated_value ? `${selected.currency} ${selected.estimated_value}` : "Not estimated"}</dd></div><div><dt>Conversion</dt><dd>{label(selected.conversion_state)}</dd></div></dl><Field label="Pipeline stage"><Select value={selected.stage_key} disabled={selected.status !== "open"} onChange={(_, data) => void stage(data.value)}>{["qualification","discovery","scoped","proposal","negotiation","lost"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></Field></section>
    <section className="pm-section"><header><h2>Proposed services</h2></header><Table aria-label="Opportunity proposed services"><TableHeader><TableRow><TableHeaderCell>Service</TableHeaderCell><TableHeaderCell>Acceptance</TableHeaderCell></TableRow></TableHeader><TableBody>{selected.services?.map((service) => <TableRow key={service.id}><TableCell>{service.service_name || service.name || "Service"}</TableCell><TableCell>{service.accepted ? "Accepted" : "Proposed"}</TableCell></TableRow>)}</TableBody></Table></section>
    <section className="pm-section"><header><div><h2>QuoteBench proposal</h2><p>PracticeEngine stores the stable reference; proposal content and pricing remain in QuoteBench.</p></div>{onOpenQuoteBench && <Button onClick={() => onOpenQuoteBench(selected.id)}>Open in QuoteBench</Button>}</header><div className="pm-add-row"><Field label="Proposal reference"><Input value={proposalId} onChange={(_, data) => setProposalId(data.value)} /></Field><Button appearance="primary" disabled={!proposalId.trim() || selected.status !== "open"} onClick={() => void linkProposal()}>Link proposal</Button></div>{selected.proposals?.length ? <Table aria-label="QuoteBench proposal references"><TableHeader><TableRow><TableHeaderCell>Proposal</TableHeaderCell><TableHeaderCell>Version</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHeader><TableBody>{selected.proposals.map((proposal, index) => <TableRow key={String(proposal.id ?? index)}><TableCell>{String(proposal.proposal_id ?? "Proposal")}</TableCell><TableCell>{String(proposal.proposal_version ?? "1")}</TableCell><TableCell><Status value={String(proposal.status ?? "created")} /></TableCell></TableRow>)}</TableBody></Table> : <p>No proposal is linked.</p>}</section>
  </section>;
  return <section className="pm-page"><Head title="Opportunities" body="Proposed services and commercial progress before client conversion and operational work." />{error && <Failure message={error} retry={load} />}
    <section className="pm-section"><header><h2>Add opportunity</h2></header><form className="pm-add-row" onSubmit={create}><Field label="Opportunity name" required><Input value={name} maxLength={240} onChange={(_, data) => setName(data.value)} /></Field><Field label="Prospect" required><Select value={prospectId} onChange={(_, data) => setProspectId(data.value)}><option value="">Select prospect</option>{prospects.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</Select></Field><Field label="Proposed service" required><Select value={serviceId} onChange={(_, data) => setServiceId(data.value)}><option value="">Select service</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Expected close"><Input type="date" value={expectedCloseDate} onChange={(_, data) => setExpectedCloseDate(data.value)} /></Field><Button appearance="primary" type="submit" disabled={!name.trim() || !prospectId || !serviceId}>Add opportunity</Button></form></section>
    <div className="pm-grid-scroll"><Table aria-label="CRM opportunities"><TableHeader><TableRow><TableHeaderCell>Relationship</TableHeaderCell><TableHeaderCell>Opportunity</TableHeaderCell><TableHeaderCell>Stage</TableHeaderCell><TableHeaderCell>Services</TableHeaderCell><TableHeaderCell>Owner / team</TableHeaderCell><TableHeaderCell>Expected close</TableHeaderCell><TableHeaderCell>Value</TableHeaderCell><TableHeaderCell>Proposal</TableHeaderCell></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell>{item.relationship_name || "Relationship"}</TableCell><TableCell><Button appearance="transparent" onClick={() => void open(item)}>{item.name}</Button></TableCell><TableCell><Status value={item.stage_key} /></TableCell><TableCell>{item.services?.map((service) => service.name).filter(Boolean).join(", ") || "None"}</TableCell><TableCell>{item.responsible_member_name || item.responsible_team_name || "Unassigned"}</TableCell><TableCell>{date(item.expected_close_date)}</TableCell><TableCell>{item.estimated_value ? `${item.currency} ${item.estimated_value}` : "Not estimated"}</TableCell><TableCell>{item.proposal_status ? <Status value={item.proposal_status} /> : "Not linked"}</TableCell></TableRow>)}</TableBody></Table></div>
  </section>;
}

function Onboarding({ context }: { context: ApiContext }) {
  const [items, setItems] = useState<OnboardingCase[]>([]), [selected, setSelected] = useState<OnboardingCase | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await api.onboardingCases(context)).items); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [context]);
  useEffect(() => { void load(); }, [load]);
  async function open(id: string) { try { setSelected((await api.onboardingCase(context, id)).item); } catch (e) { setError(errorText(e)); } }
  async function status(value: OnboardingCase["status"]) { if (!selected) return; try { await api.updateOnboardingStatus(context, selected.id, value); await open(selected.id); await load(); } catch (e) { setError(errorText(e)); } }
  if (loading) return <Loading text="Loading onboarding work" />;
  if (selected) return <section className="pm-page"><Button appearance="subtle" onClick={() => setSelected(null)}>Back to onboarding</Button><Head title={selected.client_name || "Client onboarding"} body={`${selected.opportunity_name || "Accepted opportunity"} · ${selected.engagement_name || "Engagement"}`} />{error && <Failure message={error} retry={() => void open(selected.id)} />}
    <section className="pm-section"><header><div><h2>Onboarding status</h2><p>Mandatory workflow tasks and blockers gate operational readiness.</p></div><Status value={selected.status} /></header><Field label="Status"><Select value={selected.status} disabled={["completed","cancelled"].includes(selected.status)} onChange={(_, data) => void status(data.value as OnboardingCase["status"])}>{["not_started","in_progress","blocked","ready_for_delivery","completed","cancelled"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></Field></section>
    <section className="pm-section"><header><h2>Required actions</h2></header><Table aria-label="Onboarding required actions"><TableHeader><TableRow><TableHeaderCell>Action</TableHeaderCell><TableHeaderCell>Stage</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHeader><TableBody>{selected.tasks?.map((task) => <TableRow key={task.id}><TableCell>{task.title}</TableCell><TableCell>{selected.stages?.find((stage) => stage.id === (task as typeof task & { work_stage_id?: string }).work_stage_id)?.name || "Onboarding"}</TableCell><TableCell><Status value={task.status} /></TableCell></TableRow>)}</TableBody></Table></section>
    <section className="pm-section"><header><h2>Blockers</h2></header>{selected.blockers?.length ? <Table aria-label="Onboarding blockers"><TableHeader><TableRow><TableHeaderCell>Blocker</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHeader><TableBody>{selected.blockers.map((blocker) => <TableRow key={blocker.id}><TableCell>{blocker.summary}</TableCell><TableCell><Status value={blocker.status} /></TableCell></TableRow>)}</TableBody></Table> : <p>No blockers recorded.</p>}</section>
  </section>;
  return <section className="pm-page"><Head title="Onboarding" body="Accepted clients moving through workflow-backed readiness gates into service delivery." />{error && <Failure message={error} retry={load} />}<div className="pm-grid-scroll"><Table aria-label="Onboarding work"><TableHeader><TableRow><TableHeaderCell>Client</TableHeaderCell><TableHeaderCell>Opportunity</TableHeaderCell><TableHeaderCell>Engagement</TableHeaderCell><TableHeaderCell>Workflow</TableHeaderCell><TableHeaderCell>Blockers</TableHeaderCell><TableHeaderCell>Updated</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell><Button appearance="transparent" onClick={() => void open(item.id)}>{item.client_name || "Client"}</Button></TableCell><TableCell>{item.opportunity_name || "Opportunity"}</TableCell><TableCell>{item.engagement_name || "Engagement"}</TableCell><TableCell>{item.work_title || "No template configured"}</TableCell><TableCell>{item.open_blockers ?? 0}</TableCell><TableCell>{date(item.updated_at)}</TableCell><TableCell><Status value={item.status} /></TableCell></TableRow>)}</TableBody></Table></div></section>;
}
