import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const service=await readFile(new URL("../src/practice-management.ts",import.meta.url),"utf8");
const migration=await readFile(new URL("../../../packages/database/migrations/0032_workflow_automation_operations.sql",import.meta.url),"utf8");
const worker=await readFile(new URL("../wrangler.jsonc",import.meta.url),"utf8");

test("PM-004 adds only the next sequential migration",()=>{assert.match(migration,/VALUES\('0032'/);assert.match(migration,/BEGIN;[\s\S]*COMMIT;/);});
test("workflow definitions and instances retain immutable provenance",()=>{for(const table of ["work_template_stage","work_stage"])assert.match(migration,new RegExp(`CREATE TABLE ${table}\\(`));for(const field of ["source_template_stage_id","source_template_id","source_template_version"])assert.ok(migration.includes(field));assert.match(service,/stageInstances/);});
test("workflow progression is server gated and auditable",()=>{for(const value of ["mandatory_tasks_incomplete","approval_required","predecessor_stage_incomplete","specialist_completion_required","manual_release_required"])assert.ok(service.includes(value)||service.includes("evaluateStageGates"));for(const event of ["workflow.stage_completed","workflow.blocked","workflow.unblocked","workflow.stage_started"])assert.ok(service.includes(event));});
test("dependency enforcement is tenant safe and rejects cycles below the UI",()=>{assert.match(migration,/reject_practice_task_dependency_cycle/);assert.match(migration,/dependencies must remain within one work item/);assert.match(migration,/d\.tenant_id=NEW\.tenant_id/);assert.match(service,/DEPENDENCY_CYCLE/);});
test("generic operational review remains distinct from Ledgerly technical review",()=>{assert.match(migration,/CREATE TABLE practice_review\(/);assert.match(migration,/CREATE TABLE practice_review_point\(/);assert.doesNotMatch(service,/insert into review_point\(/);assert.match(service,/SELF_APPROVAL_PROHIBITED/);assert.match(service,/OPEN_REVIEW_POINTS/);});
test("automation vocabulary is constrained idempotent and loop protected",()=>{assert.match(migration,/UNIQUE\(tenant_id,idempotency_key\)/);assert.match(migration,/jsonb_array_length\(causation_chain\)<=8/);assert.match(service,/assertAutomationChain/);assert.doesNotMatch(service,/fetch\(|webhook/i);for(const event of ["automation.executed","automation.failed"])assert.ok(service.includes(event));});
test("recurrence operations provide mutation-free previews and bounded replay",()=>{for(const route of ["recurrence-operations/dry-run","recurrence-operations/replay"])assert.ok(service.includes(route));assert.match(service,/boundedReplayRange/);assert.match(service,/if\(mode==="replay"&&outcome==="prospective"\)/);assert.match(service,/recurrence\.dry_run_completed/);});
test("scheduled execution remains explicit and production disabled by default",()=>{assert.match(worker,/"RECURRENCE_EXECUTION_CONTEXTS"\s*:\s*"\[\]"/);assert.doesNotMatch(worker,/"triggers"\s*:/);assert.match(service,/trigger_type,status[\s\S]*'scheduled','running'/);});
test("all PM-004 tenant tables use forced RLS and least privilege grants",()=>{for(const table of ["work_template_stage","work_stage","practice_review","practice_review_point","automation_rule","automation_execution","recurrence_execution","recurrence_execution_item"])assert.ok(migration.includes(`'${table}'`),table);assert.match(migration,/FORCE ROW LEVEL SECURITY/);assert.match(migration,/REVOKE ALL ON/);});
test("authorization separates functional permissions and automation entitlement",()=>{for(const permission of ["workflow.manage","workflow.advance","review.request","review.perform","review.approve","review.override","automation.view","automation.manage","automation.execute","recurrence.operations","recurrence.replay"])assert.ok(migration.includes(`'${permission}'`),permission);assert.match(migration,/practice\.automation/);assert.match(service,/"practice\.automation"/);});
